### ISSUE TITLE
Sidebar Additional

### ISSUE THREAD

**Issue by drinkingsouls** [DominicWatts/NewProduct#1]
Hi,
I've had this plugin installed for a while and it works great. I have added some widgets in my Sidebar Additional area and I have noticed that this plugin does not include the Sidebar Additional area in the layout. How can I add the Sidebar Additional area?

I have tried 
```
        <container name="div.sidebar.additional" htmlTag="div" htmlClass="sidebar sidebar-additional" after="div.sidebar.main">
            <container name="sidebar.additional" as="sidebar_additional" label="Sidebar Additional"/>
        </container>
    </referenceContainer>
```
in newproduct_index_index.xml but it doesn't add the area.
Thank you.

**Comment by drinkingsouls** [comment]
Is there any way to include the Sidebar Additional at all?
Thank you.

**Comment by drinkingsouls** [comment]
I figured this out.
In the index.xml add the update handle so it is shown as a category.

```
<!-- Sets view for Sidebar Additional widgets -->
<update handle="catalog_category_view_type_layered" />
```

**Comment by DominicWatts** [comment]
Any chance you can submit a pull request with the update
