### ISSUE TITLE
Adding Wishlist

### ISSUE THREAD

**Issue by drinkingsouls** [DominicWatts/NewProduct#2]
I've noticed that this module, the Special Offers page module and the Featured page module don't show the Add To Wishlist button, just the compare button.
For anyone looking to include this, you need to add to newproduct_index_index.xml

` 
            <block class="Magento\Cookie\Block\RequireCookie" name="require-cookie" template="Magento_Cookie::require_cookie.phtml">
                <arguments>
                    <argument name="triggers" xsi:type="array">
                        <item name="addToWishlistLink" xsi:type="string">.action.towishlist</item>
                    </argument>
                </arguments>
            </block>
            <referenceBlock name="category.product.addto">
                <block class="Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist"
                       name="category.product.addto.wishlist" as="wishlist" before="compare"
                       template="Magento_Wishlist::catalog/product/list/addto/wishlist.phtml"/>
            </referenceBlock>
            <referenceContainer name="category.product.list.additional">
                <block class="Magento\Wishlist\Block\AddToWishlist" name="category.product.list.additional.wishlist_addto" template="Magento_Wishlist::addto.phtml" />
            </referenceContainer>`

Just in case anyone finds this useful.

**Comment by DominicWatts** [comment]
Any chance you can submit a pull request with the update?
